autenticacao/urls.py
from django.urls import path
from . import views 

app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path('get_perfis/', views.get_perfis, name='get_perfis'),
    path('logout/', views.logout, name='logout'),
    path('novaSenha/', views.novaSenha, name='novaSenha'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('core/', include('core.urls')),
    path('cadastros/', include('cadastros.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("main", views.main, name="main"),
]

autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from cadastros.models import Usuario
from django.contrib import messages
from django.http import JsonResponse
from autenticacao import urls
from django.core.mail import EmailMessage

def login(request):
    if request.method == 'POST':
        email = request.POST.get('txtEmail')
        senha = request.POST.get('txtSenha')
        perfil_id = request.POST.get('slcPerfil')

        usuario = authenticate(request, username=email, password=senha)

        if(usuario is not None and perfil_id):
            perfis_usuario = usuario.perfis.filter(id=perfil_id)
            if perfis_usuario.exists():
                request.session.flush()
                auth_login(request, usuario)

                request.session['id_atual'] = usuario.id
                request.session['email_atual'] = usuario.email
                request.session['departamento_id_atual'] = usuario.departamento.id
                request.session['departamento_nome_atual'] = usuario.departamento.nome
                request.session['departamento_sigla_atual'] = usuario.departamento.sigla
                request.session['perfil_atual'] = perfis_usuario.first().nome
                request.session['perfis'] = list(usuario.perfis.values_list('nome', flat=True))
                
                request.session.set_expiry(14400)

                messages.success(request, 'Login realizado com sucesso!')
                
                if request.session.get('perfil_atual') in {'Administrador', 'Estoquista', 'Vendedor'}:
                    return redirect('core:main')
            else:
                messages.error(request, 'Perfil Inválido')
        else:
            if usuario is None:
                messages.error(request, 'Senha errada!')
            else:
                messages.error(request, 'Usuario ou senha invalido!')
    
    return render(request, 'login.html')

def get_perfis(request):
    email = request.GET.get('email', '')
    perfis = []

    if Usuario.objects.filter(email=email).exists():
        usuario = Usuario.objects.get(email=email)
        perfis = usuario.perfis.all().values('id', 'nome')
        data = {'perfis': list(perfis), 'usuario_existe': True}
    else:
        data = {'usuario_existe': False}

    return JsonResponse(data)

def logout(request):
    request.session.flush()
    auth_logout(request)
    messages.success(request, 'Logout realizado com sucesso!')
    
    return redirect('autenticacao:login')

def novaSenha(request):
    if request.method == 'POST':
        try:
            emaildestino = request.POST.get('txtEmail')
            novaSenha = request.POST.get('txtSenha')
            request.session.flush()
            email = EmailMessage(
            'Nova Senha Pypel',
            'Sua nova senha é: ' + novaSenha,
            'privada.games123@gmail.com',
            [emaildestino]
            )
            #email.attach_file('/caminho/para/seu/arquivo.pdf')  # Anexe um arquivo
            email.send()
            messages.success(request, 'Email Enviado com Sucesso!')
            usuario = Usuario.objects.get(email=emaildestino)
            usuario.set_password(novaSenha)
            usuario.save()
            messages.success(request, 'Senha Alterada com Sucesso!')
            return render(request, 'login.html')
        except:
            messages.error(request, 'ERRO 9002 - Deu ruim!')
    return render(request, 'novaSenha.html')
    

autenticacao/templates/login.html
{% extends 'index.html' %}

{% block conteudo %}
<div class="container">
    <h2>Login</h2>
    <form method="POST" action="{% url 'autenticacao:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="txtEmail">E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off">
            <div id="divEmailError" class="error-message"> </div>
        </div>
        <div class="form-group hidden-group" id="divSenha">
            <label for="txtSenha">Senha</label>
            <input type="password" class="form-control" id="txtSenha" name="txtSenha" required autocomplete="new-password">
        </div>
        <div class="form-group hidden-group" id="divPerfil">
            <label for="perfil">Perfil</label>
            <select class="form-control" id="slcPerfil" name="slcPerfil" required></select>
        </div>
        <div id="divSpace" class="space"> </div>
        <button type="submit" class="btn btn-light">Entrar</button>
        <a href="#" id="btnEsqueciSenha" class="btn btn-light">Esqueci minha senha</a>
    </form>
</div>

<script>
    $(document).ready(function() {
        $('#txtEmail').on('input', function() {
            var email = $(this).val();
            $('#divPerfil').addClass('hidden-group');
            $('#divSenha').addClass('hidden-group');
            $('#slcPerfil').empty();
            $('#divEmailError').text(' ').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:get_perfis' %}",
                    data: {'email': email},
                    success: function(data) {
                        if (data.usuario_existe) {
                            if (data.perfis.length > 0) {
                                $('#slcPerfil').empty();
                                data.perfis.forEach(function(perfil) {
                                    $('#slcPerfil').append(new Option(perfil.nome, perfil.id));
                                });
                                $('#divPerfil').removeClass('hidden-group');
                                $('#divSenha').removeClass('hidden-group');
                            } else {
                                toastr.error("Nenhum perfil encontrado para este e-mail.", "Erro");
                            }
                        } else {
                            $('#divEmailError').text('.').addClass('visible');
                        }
                    }
                });
            }
        });

        $('#btnEsqueciSenha').click(function(event) {
            event.preventDefault();
            toastr.info('Se você esqueceu sua senha contate o administrador do sistema.');
        });
    });
</script>
{% endblock %}

autenticacao/templates/novaSenha.html
{% extends 'index.html' %}

{% block conteudo %}
<div class="container">
    <h2>Trocar Senha</h2>
    <form method="POST" action="{% url 'autenticacao:novaSenha' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="txtEmail">E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off">
            <div id="divEmailError" class="error-message"> </div>
        </div>
        <div class="form-group hidden-group" id="divSenha">
            <label for="txtNovaSenha">Nova Senha</label>
            <input type="password" class="form-control" id="txtSenha" name="txtSenha" required autocomplete="new-password">
        </div>
        {% comment %} <div class="form-group hidden-group" id="divPerfil">
            <label for="perfil">Perfil</label>
            <select class="form-control" id="slcPerfil" name="slcPerfil" required></select>
        </div> {% endcomment %}
        <div id="divSpace" class="space"> </div>
        <button type="submit" class="btn btn-light">Enviar E-mail</button>
        <a href="#" id="btnVoltar" class="btn btn-light">Voltar</a>
    </form>
</div>

<script>
    $(document).ready(function() {
        $('#txtEmail').on('input', function() {
            var email = $(this).val();
            $('#divPerfil').addClass('hidden-group');
            $('#divSenha').addClass('hidden-group');
            $('#divEmailError').text(' ').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:get_perfis' %}",
                    data: {'email': email},
                    success: function(data) {
                        if (data.usuario_existe) {
                            $('#divSenha').removeClass('hidden-group');
                        } else {
                            $('#divEmailError').text('.').addClass('visible');
                        }
                    }
                });
            }
        });

        $('#btnVoltar').click(function(event) {
            event.preventDefault();
            toastr.info('Voltou???');
            window.location.href = "http://127.0.0.1:8000/";
        });
    });
</script>
{% endblock %}