cadastros/urls.py
from django.urls import path
from . import views

app_name = "cadastros"

urlpatterns = [

    #CADASTRO DE DEPARTAMENTO
    path("departamentos/", views.departamentos, name="departamentos"),
    path("obter_departamento_por_id/", views.obter_departamento_por_id, name="obter_departamento_por_id"),
    path("excluir_departamento/", views.excluir_departamento, name="excluir_departamento"),
    path("pesquisar_departamento_por_nome/", views.pesquisar_departamento_por_nome, name="pesquisar_departamento_por_nome"),
    #------------------------------------
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('core/', include('core.urls')),
    path('cadastros/', include('cadastros.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("main", views.main, name="main"),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.deletion import ProtectedError

class Departamento(models.Model):
    nome = models.CharField(max_length=500)
    sigla = models.CharField(max_length=30)
    
    def delete(self, *args, **kwargs):
        if self.usuario_set.exists():
            raise ProtectedError(
                "Não é possível excluir este departamento, pois ele possui usuarios vinculados.",
                self
            )
        super().delete(*args, **kwargs)
        
    def __str__(self):
        return self.nome

class Perfil(models.Model):
    nome = models.CharField(max_length=100, unique=True)

    def delete(self, *args, **kwargs):
        if self.usuario_set.exists():
            raise ProtectedError(
                "Não é possível excluir este perfil, pois ele possui usuarios vinculados.",
                self
            )
        super().delete(*args, **kwargs)
        
    def __str__(self):
        return self.nome
    
class UsuarioManager(BaseUserManager):
    def create_user(self, email, nome, password=None):
        if not email:
            raise ValueError('O usuário deve ter um endereço de e-mail')
        user = self.model(email=self.normalize_email(email), nome=nome)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nome, password=None):
        user = self.create_user(email, nome, password)
        user.is_admin = True
        user.save(using=self._db)
        return user

class Usuario(AbstractBaseUser):
    nome = models.CharField(max_length=300)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT)
    perfis = models.ManyToManyField(Perfil)

    objects = UsuarioManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin 

        
    def tem_perfil(self, perfil_nome):
        return self.perfis.filter(nome=perfil_nome).exists()

cadastros/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.db.models import Q, F, Count, Subquery, OuterRef, FloatField, Sum, ExpressionWrapper
from .models import Usuario, Perfil, Departamento
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

#CADASTRO DE DEPARTAMENTOS
@login_required
def departamentos(request):
    if request.session.get('perfil_atual') not in {'Administrador'}:
        messages.error(request, 'Você não é administrador!')
        return redirect('core:main')
    
    if request.method == "POST":
        acao = request.POST.get("btnAcao")

        if acao == "novo_departamento":
            nome = request.POST.get('txtNome')
            
            if (nome.strip().lower() == 'Geral'):
                messages.error(request, 'Você não pode cadastrar um departamento chamado "Geral", pois esse nome é reservado para o sistema! Use outro.')
                return redirect('cadastros:departamentos')
            
            sigla = request.POST.get('txtSigla')

            if Departamento.objects.filter(nome=nome).exists():
                messages.error(request, 'Nome de departamento já cadastrado nesta unidade!')
                return redirect('cadastros:departamentos')

            departamento = Departamento(
                nome=nome,
                sigla=sigla,
            )
            
            departamento.save()

            messages.success(request, 'Departamento cadastrado com sucesso!')
            return redirect('cadastros:departamentos')
        
        elif acao =='alterar_departamento':
            departamento_id = request.POST.get('txtId')
            departamento = Departamento.objects.get(id=departamento_id)

            nome = request.POST.get('txtNome')
            sigla = request.POST.get('txtSigla')

            if (nome == 'Geral' or Departamento.objects.filter(nome=nome).exists()):
                messages.error(request, 'Você não pode cadastrar um departamento chamado "Geral", pois esse nome é reservado para o sistema! Use outro.')
                return redirect('cadastros:departamentos')
            
            departamento.nome = nome
            departamento.sigla = sigla
            departamento.save()

            messages.success(request, 'Departamento alterado com sucesso')
            return redirect('cadastros:departamentos')


    departamento_lista = Departamento.objects.all().exclude(nome__iexact="Geral").order_by('nome')
    paginator = Paginator(departamento_lista, settings.NUMBER_GRID_PAGES)
    numero_pagina = request.GET.get('page')
    page_obj = paginator.get_page(numero_pagina)

    return render(request, 'departamentos.html', {'page_obj': page_obj})

@login_required
def obter_departamento_por_id(request):
    departamento_id = request.GET.get('departamento_id', None)
    departamento = Departamento.objects.get(id=departamento_id)

    departamento_dados = {
        'id': departamento.id,
        'nome': departamento.nome,
        'sigla': departamento.sigla
    }

    return JsonResponse(departamento_dados)

@login_required
def excluir_departamento(request):
    if request.method == 'POST':
        departamento_id = request.POST.get('departamento_id')
        departamento = Departamento.objects.filter(id=departamento_id).first()

        if (departamento.usuario_set.exists()):
            return JsonResponse({'success': False, 'messages' :'Não é possível excluir este departamento, pois ele possui usuários vinculados.'})

        departamento.delete()

        return JsonResponse({'success': True, 'messages' :'Departamento excluído com sucesso!'})

@login_required
def pesquisar_departamento_por_nome(request):
    departamento_nome = request.GET.get('departamento_nome', '')
    numero_pagina = request.GET.get('page')

    departamento_lista = Departamento.objects.filter(nome__icontains=departamento_nome).exclude(nome__iexact="Geral").order_by('nome')
    paginator = Paginator(departamento_lista, settings.NUMBER_GRID_PAGES)
    page_obj = paginator.get_page(numero_pagina)

    return JsonResponse({
        'html': render_to_string('departamentos_table.html', {'page_obj': page_obj, 'query': departamento_nome, 'request': request})
    })

cadastros/templates/departamentos.html
{% extends 'master.html' %}
{% load static %}

{% block conteudo %}

<br>
<div class="container">

    <div class="form-group row align-items-center mb-4">
        <div class="col-12 text-center">
            <h1 class="display-5 font-weight-bold text-primary">
                Cadastro de Departamentos
            </h1>
            <hr class="mt-2 mb-3 border-primary">
        </div>
    </div>

    <fieldset class="fieldset-custom">
        <legend>
            {% if page_obj.paginator.count == 0 %}
                Nenhum registro encontrado
            {% elif page_obj.paginator.count == 1 %}
                1 registro encontrado
            {% else %}
                {{ page_obj.paginator.count }} registros encontrados
            {% endif %}
        </legend>

        <div class="form-group row align-items-center">
            <div class="col-auto">
                <img src="{% static 'img/search.png' %}" width=20px height="20px" alt="Pesquisar">
            </div>
            <div class="text-left">
                <label for="txtBuscaNome" class="col-form-label"> Pesquisar por nome: </label>
            </div>
            <div class="col">
                <input type="text" class="form-control" id="txtBuscaNome" 
                    placeholder="Digite o nome do departamento" value="{{ query }}">
            </div>
        </div>

        <div id="departamentos-table">
            {% include 'departamentos_table.html' %}
        </div>
    </fieldset>

    <hr>

    <fieldset class="fieldset-custom">
        <legend id="formLegend">Novo departamento</legend>
        <form class="needs-validation" method="POST" action="{% url 'cadastros:departamentos' %}" novalidate>

            {% csrf_token %}

            <!-- código do departamento -->
            <input type="hidden" name="txtId" id="txtId" value="">

            <!-- nome -->
            <div class="form-group row align-items-center has-validation">
                <label for="txtNome" class="col-sm-2 col-form-label text-left">Nome:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Digite o nome" name="txtNome" id="txtNome" value="" required>
                </div>
                <div class="invalid-feedback text-left">
                    O nome é obrigatório!
                </div>
            </div>

            <!-- sigla -->
            <div class="form-group row align-items-center has-validation">
                <label for="txtSigla" class="col-sm-2 col-form-label text-left">Sigla:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="Digite a sigla" name="txtSigla" id="txtSigla" value="" required>
                </div>
                <div class="invalid-feedback text-left">
                    A sigla é obrigatória!
                </div>
            </div>

            <!-- ações -->
            <div class="form-group row align-items-center">
                <div class="col-sm-12 text-right">
                    
                    <a href="{% url 'cadastros:departamentos' %}" class="btn btn-info" id="btnNovoDepartamento" style="display: none;">
                        <img src="{% static 'img/create.png' %}" width="20" height="20" alt="Voltar ao modo de inclusão">
                        Voltar ao modo de inclusão
                    </a>

                    <button type="submit" 
                            class="btn btn-primary" 
                            name="btnAcao" 
                            id="btnAcao" 
                            value="novo_departamento">Salvar Novo Departamento</button>

                </div>
            </div>

        </form>
    </fieldset>
    CONTINUAR DAQUI...
    
</div>

<!-- janela de confirmação de exclusão-->
<div class="modal fade" id="jnlExcluir" tabindex="-1" role="dialog" aria-labelledby="jnlExcluirRotulo" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="jnlExcluirRotulo">
                    Confirmação de exclusão
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Deseja excluir?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    Cancelar
                </button>
                <button type="button" class="btn btn-danger" id="jnlExcluirBtnExcluir">
                    Excluir
                </button>
            </div>
        </div>
    </div>
</div>


<!-- scripts específicos do cadastro de departamentos -->
<script>

    //função para carregar os dados do departamento no formulário
    function carregaDadosDepartamento(departamento_id){
        $.ajax({
            url: '{% url "cadastros:obter_departamento_por_id" %}',
            data: {
                departamento_id: departamento_id
            },
            dataType: 'json',
            success: function(departamento_dados){
                $('#txtId').val(departamento_dados.id);
                $('#txtNome').val(departamento_dados.nome);
                $('#txtSigla').val(departamento_dados.sigla);

                $('#formLegend').text('Alterar departamento');
                $('#btnAcao').text('Alterar departamento').val('alterar_departamento');
                $('#btnNovoDepartamento').show();
            }
        });
    }

    //click na linha do grid
    function clickNoGrid(){
        $('.departamento-row').click(function(){

            $('.departamento-row').removeClass('table-primary table-bordered');
            $('this').addClass('table-primary table-bordered');

            var departamento_id = $(this).data('id');
            carregaDadosDepartamento(departamento_id);
        
            //codigo para exibir a janela de confirmação de exclusão
            $('.delete-btn').click( function() {
                apagarDepartamentoPorId = $(this).data('id');
                $('#jnlExcluir').modal('show');
            });
        });
    }

    $('#jnlExcluirBtnExcluir').click( function() {
        $.ajax({
            url: '{% url "cadastros:excluir_departamento" %}',
            method: 'POST',
            data: {
                'departamento_id': apagarDepartamentoPorId,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function(response){
                if (response.success) {
                    toastr.success(response.message);
                    location.reload();
                }
                else{
                    toastr.error(response.message);
                }
            }
        });
    });


    //buscar departamentos por nome
    function filtraDepartamentoPorNome(){
        let departamento_nome = $('#txtBuscaNome').val();
        $.ajax({
            url: '{% url "cadastros:pesquisar_departamento_por_nome" %}',
            method: 'GET',
            data: {
                'departamento_nome': departamento_nome
            },
            success: function(data){
                $('#departamentos-table').html(data.html);
                clickNoGrid();
            }
        });
    }


    //evento de imput no campo de busca
    $('#txtBuscaNome').on('input', function(){
        filtraDepartamentoPorNome();
    });


    //função que carrega as funções e eventos da página
    $('document').ready(function() {

        //anexa o evento de click ao grid
        clickNoGrid();

        (() => {
            'use strict'
            //carrega os formularios do bootstrap que tem validacao customizada
            const forms = document.querySelectorAll('.needs-validation')
            //loop nesses formularios para evitar o envio do formulário se ele nao for valido
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }
                    form.classList.add('was-validated')
                }, false)
            })
        })();
    }); 

</script>

{% endblock %}

cadastros/templates/departamentos_table.html
{% load static %}

<!-- grid -->
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">NOME</th>
            <th scope="col">SIGLA</th>
            <th scope="col">AÇÕES</th>
        </tr>
    </thead>
    <tbody>
        {% for departamento in page_obj %}
        <tr class="departamento-row" data-id="{{ departamento.id }}">
            <td>{{ forloop.counter }}</td>
            <td>{{ departamento.nome }}</td>
            <td>{{ departamento.sigla }}</td>
            <td>
                <button class="btn btn-sm delete-btn" data-id="{{ departamento.id }}">
                    <img src="{% static 'img/delete.png' %}" width="20px" height="20px" alt="Excluir">
                </button>
                <button class="btn btn-sm">
                    <img src="{% static 'img/update.png' %}" width="20px" height="20px" alt="Alterar">
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- paginacao do grid -->
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1&query={{ query }}">&laquo; primeira</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&query={{ query }}">&lsaquo; anterior</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo; primeira</span></li>
            <li class="page-item disabled"><span class="page-link">&lsaquo; anterior</span></li>
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><span class="page-link">{{ num }}</span></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}&query={{ query }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&query={{ query }}">próxima &rsaquo;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&query={{ query }}">última &raquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">próxima &rsaquo;</span></li>
            <li class="page-item disabled"><span class="page-link">última &raquo;</span></li>
        {% endif %}
    </ul>
</nav>