autenticacao/urls.py
from django.urls import path
from . import views 

app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path('get_perfis/', views.get_perfis, name='get_perfis'),
    path('logout/', views.logout, name='logout'),
    path('novaSenha/', views.novaSenha, name='novaSenha'),
]

cadastros/urls.py
from django.urls import path
from . import views

app_name = "cadastros"

urlpatterns = [

    #CADASTRO DE DEPARTAMENTO
    path("departamentos/", views.departamentos, name="departamentos"),
    path("obter_departamento_por_id/", views.obter_departamento_por_id, name="obter_departamento_por_id"),
    path("excluir_departamento/", views.excluir_departamento, name="excluir_departamento"),
    path("pesquisar_departamento_por_nome/", views.pesquisar_departamento_por_nome, name="pesquisar_departamento_por_nome"),
    #------------------------------------
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('core/', include('core.urls')),
    path('cadastros/', include('cadastros.urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("main", views.main, name="main"),
]

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

@login_required
def main(request):
    return render(request, 'main.html')

core/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>:: PYPEL ::</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
</head>
<body>
    <div class="container-fluid vh-100 d-flex flex-column">
        <div class="row flex-grow-1">
            <div class="col col-blue d-flex flex-column justify-content-center" style="background-color: #efc9c9">
                <!-- Conteúdo carregado dinamicamente -->
                <div class="content">
                    {% block conteudo %}
                    {% endblock %}
                </div>
            </div>
            <div class="col col-white d-flex flex-column justify-content-center align-items-center">
                <div class="text-center">
                    <img src="{% static 'img/logo.png'%}" alt="Logomarca do Sistema de Gerenciamento de Papelaria" width="300px">
                    <div class="footer-text text-center py-3">
                        Este sistema está licenciado sob 
                        <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer" style="color: #0000FF;">
                            Licença Creative Commons&copy; 4.0 
                        </a> 
                        <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons"> <br>
                        Disponível para download em 
                        <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer" style="color: #0000FF;">
                            github.com/ciniro/pypel
                        </a>
                        <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">
                        <button id="btnSobre" class="btn btn-outline-secondary p-0">Sobre</button>
                    </div>
                </div>
            </div>
        </div>
    </div>    
    
    <!-- sobre -->
    <div class="modal fade" id="jnlSobre" tabindex="-1" role="dialog" aria-labelledby="jnlSobreRotulo" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="jnlSobreRotulo">Sobre o PYPEL</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-justify">
                    <p>
                        O PYPEL é um sistema de gerenciamento de papelaria que permite a gestão do estoque de produtos 
                        fornecendo um sistema de entrada e uma tela de venda que permite dar saída nos itens cadastrados no estoque.
                    </p>
                    <p>
                        O sistema é utilizado pelo Prof. Dr. Ciniro Nametala (<a href="http://lattes.cnpq.br/3258604768114823">lattes</a>) 
                        com o apoio das turmas da disciplina de Programação WEB do curso de Bacharelado em Engenharia de Computação do Instituto Federal de Minas Gerais - <i>Campus</i> Bambuí, e está licenciado sob 
                        <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
                            Licença Creative Commons&copy; 4.0 
                        </a> 
                        <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons">.
                    </p>
                    <p>
                        O PYPEL foi desenvolvido em <a href="https://www.python.org/" target="_blank" rel="noopener noreferrer">
                            Python
                        </a> <img src="{% static 'img/python.png' %}" width="15px" alt="Python">, 
                        <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Django</a>
                        <img src="{% static 'img/django.png' %}" width="15px" alt="Django"> e 
                        <a href="https://www.postgresql.org/" target="_blank" rel="noopener noreferrer">PostgreSQL</a>
                        <img src="{% static 'img/postgresql.png' %}" width="15px" alt="PostgreSQL">. 
                        O código fonte, juntamente com as instruções de instalação, estão disponíveis para <i>download</i> em 
                        <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer">
                            github.com/ciniro/pypel
                        </a>
                        <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">. Você pode contribuir com o projeto, reportando erros, sugerindo melhorias ou mesmo implementando novas funcionalidades você mesmo. Por favor, use o GitHub para isso.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "3000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        toastr.error("{{ message }}", "Erro");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        toastr.success("{{ message }}", "Sucesso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                        toastr.warning("{{ message }}", "Aviso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        toastr.info("{{ message }}", "Atenção");
                    {% endif %}
                {% endfor %}
            {% endif %}

            //sobre
            $('#btnSobre').click(function() {
                $('#jnlSobre').modal('show');
            });
        });
    </script>

</body>
</html>

core/templates/main.html
{% extends 'master.html' %}

{% load static %}

{% block conteudo %}
<div>
    <img src="{% static 'img/background.png'%}" 
        alt="Logomarca do Sistema de Gerenciamento de Papelaria"
        style="top: 0; left: 0; width: 75%;">
</div>
{% endblock %}

core/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>:: PYPEL ::</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/crud.css' %}">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    
</head>
<body>
    <div class="flex-wrapper">
        <header id="menu_navegacao">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
                {% if request.session.perfil_atual == 'Administrador' %}
                <a class="navbar-brand" href="{% url 'core:main' %}">HOME</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarMenuExemplo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Arquivo
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarMenuExemplo">
                                <a class="dropdown-item" href="#">Meus dados</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'autenticacao:logout' %}">
                                    <img src="{% static 'img/my_logout.png' %}" width="20px" alt="Logout">
                                    Sair
                                </a>
                        {% if request.session.perfil_atual == 'Administrador' %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarMenuExemplo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Pessoal
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarMenuExemplo">
                                <a class="dropdown-item" href="{% url 'cadastros:departamentos' %}">Departamentos</a>
                                <a class="dropdown-item" href="#">
                                    <img src="{% static 'img/users.png' %}" width="20px" alt="Logout">
                                    Usuários
                                </a>
                            </div>
                        </li>
                        {% endif %}
                        {% if request.session.perfil_atual == 'Estoquista' or request.session.perfil_atual == 'Administrador' %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarMenuExemplo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Estoque
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarMenuExemplo">
                                <a class="dropdown-item" href="#">Produtos</a>
                            </div>
                        </li>
                        {% endif %}
                        {% if request.session.perfil_atual == 'Vendedor' or request.session.perfil_atual == 'Administrador' %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarMenuExemplo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Vendas
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarMenuExemplo">
                                <a class="dropdown-item" href="#">Vendas</a>
                            </div>
                        </li>
                        {% endif %}
                        {% if request.session.perfil_atual == 'Administrador' %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarMenuExemplo" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Relatórios
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarMenuExemplo">
                                <a class="dropdown-item" href="#">Lista de Usuários</a>
                                <a class="dropdown-item" href="#">Balanço</a>
                                <a class="dropdown-item" href="#">Contabilidade</a>
                            </div>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </nav>
        </header>

        <div class="content">
            {% block conteudo %}
            {% endblock %}
        </div>

        <!-- janela sobre -->
        <div class="modal fade" id="jnlSobre" tabindex="-1" role="dialog" aria-labelledby="jnlSobreRotulo" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="jnlSobreRotulo">Sobre o PYPEL</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-justify">
                        <p>
                            O PYPEL é um sistema de gerenciamento de papelaria que permite a gestão do estoque de produtos 
                            fornecendo um sistema de entrada e uma tela de venda que permite dar saída nos itens cadastrados no estoque.
                        </p>
                        <p>
                            O sistema é utilizado pelo Prof. Dr. Ciniro Nametala (<a href="http://lattes.cnpq.br/3258604768114823">lattes</a>) 
                            com o apoio das turmas da disciplina de Programação WEB do curso de Bacharelado em Engenharia de Computação do Instituto Federal de Minas Gerais - <i>Campus</i> Bambuí, e está licenciado sob 
                            <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
                                Licença Creative Commons&copy; 4.0 
                            </a> 
                            <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons">.
                        </p>
                        <p>
                            O PYPEL foi desenvolvido em <a href="https://www.python.org/" target="_blank" rel="noopener noreferrer">
                                Python
                            </a> <img src="{% static 'img/python.png' %}" width="15px" alt="Python">, 
                            <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Django</a>
                            <img src="{% static 'img/django.png' %}" width="15px" alt="Django"> e 
                            <a href="https://www.postgresql.org/" target="_blank" rel="noopener noreferrer">PostgreSQL</a>
                            <img src="{% static 'img/postgresql.png' %}" width="15px" alt="PostgreSQL">. 
                            O código fonte, juntamente com as instruções de instalação, estão disponíveis para <i>download</i> em 
                            <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer">
                                github.com/ciniro/pypel
                            </a>
                            <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">. Você pode contribuir com o projeto, reportando erros, sugerindo melhorias ou mesmo implementando novas funcionalidades você mesmo. Por favor, use o GitHub para isso.
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <footer id="rodape">
            <div class="footer-text text-align-center">
                PYPEL - Sistema de Gerenciamento de Papelaria <button id="btnSobre">Sobre</button><br>
                Este sistema está licenciado sob 
                <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer" style="color: #B0C4DE;">
                    Licença Creative Commons&copy; 4.0 
                </a> 
                <img src="{% static 'img/creativecommons.png' %}" width="45px" alt="Creative Commons"> <br>
                Disponível para download em 
                <a href="https://github.com/ciniro/pypel" target="_blank" rel="noopener noreferrer" style="color: #B0C4DE;">
                    github.com/ciniro/pypel
                </a>
                <img src="{% static 'img/github.png' %}" width="15px" alt="GitHub">
            </div>
        </footer>
    </div>

    <script>
        //exibir modal sobre
        $('#btnSobre').click(function() {
            $('#jnlSobre').modal('show');
        });

        //eventos que serao usados no caso do cadastro ser carregado em forma modal
        window.addEventListener('load', function() {
            if (window.opener) {
                var header = document.getElementById('rodape');
                var footer = document.getElementById('menu_navegacao');
                
                if (header) header.style.display = 'none';
                if (footer) footer.style.display = 'none';
            }
        });

        window.onbeforeunload = function() {
            if (window.opener && !window.opener.closed) {
                window.opener.location.reload();
                window.opener.window.opener.desabilitaInteracoes();                
            }
        };
        //---------------------------------
        
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };

            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        toastr.error("{{ message }}", "Erro");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        toastr.success("{{ message }}", "Sucesso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                        toastr.warning("{{ message }}", "Aviso");
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        toastr.info("{{ message }}", "Atenção");
                    {% endif %}
                {% endfor %}
            {% endif %}
        });
    </script>
</body>
</html>